/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBerachainRewardsVault } from './IBerachainRewardsVault';
export type { KumaRewardToken } from './KumaRewardToken';
