/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exchangeStargateV2AdapterSol from './ExchangeStargateV2Adapter.sol';
export type { exchangeStargateV2AdapterSol };
