/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exchangeLayerZeroAdapterSol from './ExchangeLayerZeroAdapter.sol';
export type { exchangeLayerZeroAdapterSol };
