/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exchangeStargateAdapterSol from './ExchangeStargateAdapter.sol';
export type { exchangeStargateAdapterSol };
