/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storkIndexAndOraclePriceAdapterSol from './StorkIndexAndOraclePriceAdapter.sol';
export type { storkIndexAndOraclePriceAdapterSol };
export type { KumaIndexAndOraclePriceAdapter } from './KumaIndexAndOraclePriceAdapter';
export type { PythIndexPriceAdapter } from './PythIndexPriceAdapter';
