/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../../common';

export interface INativeConverterInterface extends Interface {
  getFunction(
    nameOrSignature: 'convert' | 'zkBWUSDC' | 'zkUSDCe',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'convert',
    values: [AddressLike, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'zkBWUSDC', values?: undefined): string;
  encodeFunctionData(functionFragment: 'zkUSDCe', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'convert', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'zkBWUSDC', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'zkUSDCe', data: BytesLike): Result;
}

export interface INativeConverter extends BaseContract {
  connect(runner?: ContractRunner | null): INativeConverter;
  waitForDeployment(): Promise<this>;

  interface: INativeConverterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  convert: TypedContractMethod<
    [receiver: AddressLike, amount: BigNumberish, permitData: BytesLike],
    [void],
    'nonpayable'
  >;

  zkBWUSDC: TypedContractMethod<[], [string], 'nonpayable'>;

  zkUSDCe: TypedContractMethod<[], [string], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'convert',
  ): TypedContractMethod<
    [receiver: AddressLike, amount: BigNumberish, permitData: BytesLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'zkBWUSDC',
  ): TypedContractMethod<[], [string], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'zkUSDCe',
  ): TypedContractMethod<[], [string], 'nonpayable'>;

  filters: {};
}
