/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from 'ethers';
import type { Signer, ContractDeployTransaction, ContractRunner } from 'ethers';
import type { NonPayableOverrides } from '../../../common';
import type {
  SortedStringSet,
  SortedStringSetInterface,
} from '../../../contracts/libraries/SortedStringSet';

const _abi = [
  {
    inputs: [],
    name: 'NOT_FOUND',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

const _bytecode =
  '0x608080604052346100195760b2908161001f823930815050f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c635ffce20a14602657600080fd5b60007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc360112607757807fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff60209252f35b600080fdfea2646970667358221220a2f03de3d56b41012fcc1bfce356c6578d7ea1ed8ab1be5dc4698c3dc950b31d64736f6c63430008120033';

type SortedStringSetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SortedStringSetConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SortedStringSet__factory extends ContractFactory {
  constructor(...args: SortedStringSetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string },
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SortedStringSet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SortedStringSet__factory {
    return super.connect(runner) as SortedStringSet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SortedStringSetInterface {
    return new Interface(_abi) as SortedStringSetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): SortedStringSet {
    return new Contract(address, _abi, runner) as unknown as SortedStringSet;
  }
}
