/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exchangeWalletStateAggregatorSol from './ExchangeWalletStateAggregator.sol';
export type { exchangeWalletStateAggregatorSol };
