/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../../common';

export interface IGovernanceMockCustodianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'migrateAsset'
      | 'setAssetMigrator'
      | 'setExchange'
      | 'setGovernance',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'migrateAsset',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setAssetMigrator',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setExchange',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setGovernance',
    values: [AddressLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'migrateAsset',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setAssetMigrator',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setExchange',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setGovernance',
    data: BytesLike,
  ): Result;
}

export interface IGovernanceMockCustodian extends BaseContract {
  connect(runner?: ContractRunner | null): IGovernanceMockCustodian;
  waitForDeployment(): Promise<this>;

  interface: IGovernanceMockCustodianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  migrateAsset: TypedContractMethod<
    [sourceAsset: AddressLike],
    [string],
    'nonpayable'
  >;

  setAssetMigrator: TypedContractMethod<
    [assetMigrator: AddressLike],
    [void],
    'nonpayable'
  >;

  setExchange: TypedContractMethod<
    [exchange: AddressLike],
    [void],
    'nonpayable'
  >;

  setGovernance: TypedContractMethod<
    [governance: AddressLike],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'migrateAsset',
  ): TypedContractMethod<[sourceAsset: AddressLike], [string], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setAssetMigrator',
  ): TypedContractMethod<[assetMigrator: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setExchange',
  ): TypedContractMethod<[exchange: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setGovernance',
  ): TypedContractMethod<[governance: AddressLike], [void], 'nonpayable'>;

  filters: {};
}
