/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../../common';

export type IndexPriceStruct = {
  baseAssetSymbol: string;
  timestampInMs: BigNumberish;
  price: BigNumberish;
};

export type IndexPriceStructOutput = [
  baseAssetSymbol: string,
  timestampInMs: bigint,
  price: bigint,
] & { baseAssetSymbol: string; timestampInMs: bigint; price: bigint };

export interface IIndexPriceAdapterInterface extends Interface {
  getFunction(
    nameOrSignature: 'setActive' | 'validateIndexPricePayload',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'setActive',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'validateIndexPricePayload',
    values: [BytesLike],
  ): string;

  decodeFunctionResult(functionFragment: 'setActive', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'validateIndexPricePayload',
    data: BytesLike,
  ): Result;
}

export interface IIndexPriceAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): IIndexPriceAdapter;
  waitForDeployment(): Promise<this>;

  interface: IIndexPriceAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  setActive: TypedContractMethod<[exchange: AddressLike], [void], 'nonpayable'>;

  validateIndexPricePayload: TypedContractMethod<
    [payload: BytesLike],
    [IndexPriceStructOutput],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'setActive',
  ): TypedContractMethod<[exchange: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'validateIndexPricePayload',
  ): TypedContractMethod<
    [payload: BytesLike],
    [IndexPriceStructOutput],
    'nonpayable'
  >;

  filters: {};
}
