/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../common';

export interface FundingMultiplierMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'fundingMultipliers'
      | 'loadAggregatePayment'
      | 'publishFundingMultiplier',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'fundingMultipliers',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadAggregatePayment',
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'publishFundingMultiplier',
    values: [BigNumberish],
  ): string;

  decodeFunctionResult(
    functionFragment: 'fundingMultipliers',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadAggregatePayment',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'publishFundingMultiplier',
    data: BytesLike,
  ): Result;
}

export interface FundingMultiplierMock extends BaseContract {
  connect(runner?: ContractRunner | null): FundingMultiplierMock;
  waitForDeployment(): Promise<this>;

  interface: FundingMultiplierMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  fundingMultipliers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        fundingMultiplier0: bigint;
        fundingMultiplier1: bigint;
        fundingMultiplier2: bigint;
        fundingMultiplier3: bigint;
      },
    ],
    'view'
  >;

  loadAggregatePayment: TypedContractMethod<
    [
      fromTimestampInMs: BigNumberish,
      toTimestampInMs: BigNumberish,
      lastFundingRatePublishTimestampInMs: BigNumberish,
      positionSize: BigNumberish,
    ],
    [bigint],
    'view'
  >;

  publishFundingMultiplier: TypedContractMethod<
    [newFundingMultiplier: BigNumberish],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(nameOrSignature: 'fundingMultipliers'): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        fundingMultiplier0: bigint;
        fundingMultiplier1: bigint;
        fundingMultiplier2: bigint;
        fundingMultiplier3: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadAggregatePayment',
  ): TypedContractMethod<
    [
      fromTimestampInMs: BigNumberish,
      toTimestampInMs: BigNumberish,
      lastFundingRatePublishTimestampInMs: BigNumberish,
      positionSize: BigNumberish,
    ],
    [bigint],
    'view'
  >;
  getFunction(
    nameOrSignature: 'publishFundingMultiplier',
  ): TypedContractMethod<
    [newFundingMultiplier: BigNumberish],
    [void],
    'nonpayable'
  >;

  filters: {};
}
