/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../common';

export interface OraclePriceAdapterMockInterface extends Interface {
  getFunction(
    nameOrSignature: 'loadPriceForBaseAssetSymbol' | 'setActive',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'loadPriceForBaseAssetSymbol',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setActive',
    values: [AddressLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'loadPriceForBaseAssetSymbol',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setActive', data: BytesLike): Result;
}

export interface OraclePriceAdapterMock extends BaseContract {
  connect(runner?: ContractRunner | null): OraclePriceAdapterMock;
  waitForDeployment(): Promise<this>;

  interface: OraclePriceAdapterMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  loadPriceForBaseAssetSymbol: TypedContractMethod<
    [arg0: string],
    [bigint],
    'view'
  >;

  setActive: TypedContractMethod<[arg0: AddressLike], [void], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'loadPriceForBaseAssetSymbol',
  ): TypedContractMethod<[arg0: string], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'setActive',
  ): TypedContractMethod<[arg0: AddressLike], [void], 'nonpayable'>;

  filters: {};
}
