/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../common';

export interface WithdrawExitValidationsMockInterface extends Interface {
  getFunction(
    nameOrSignature: 'validateExitQuoteQuantityAndCoerceIfNeeded',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'validateExitQuoteQuantityAndCoerceIfNeeded',
    values: [boolean, BigNumberish],
  ): string;

  decodeFunctionResult(
    functionFragment: 'validateExitQuoteQuantityAndCoerceIfNeeded',
    data: BytesLike,
  ): Result;
}

export interface WithdrawExitValidationsMock extends BaseContract {
  connect(runner?: ContractRunner | null): WithdrawExitValidationsMock;
  waitForDeployment(): Promise<this>;

  interface: WithdrawExitValidationsMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  validateExitQuoteQuantityAndCoerceIfNeeded: TypedContractMethod<
    [isExitFundWallet: boolean, walletQuoteQuantityToWithdraw: BigNumberish],
    [bigint],
    'view'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'validateExitQuoteQuantityAndCoerceIfNeeded',
  ): TypedContractMethod<
    [isExitFundWallet: boolean, walletQuoteQuantityToWithdraw: BigNumberish],
    [bigint],
    'view'
  >;

  filters: {};
}
