/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from 'ethers';
import type { Signer, ContractDeployTransaction, ContractRunner } from 'ethers';
import type { NonPayableOverrides } from '../../../common';
import type {
  StringMock,
  StringMockInterface,
} from '../../../contracts/test/StringMock';

const _abi = [
  {
    inputs: [
      {
        internalType: 'string',
        name: 'self',
        type: 'string',
      },
      {
        internalType: 'string',
        name: 'prefix',
        type: 'string',
      },
    ],
    name: 'startsWith',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
] as const;

const _bytecode =
  '0x6080806040523461001657610398908161001c8239f35b600080fdfe6080604052600436101561001257600080fd5b6000803560e01c63adf069ea1461002857600080fd5b346100a65760407ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc3601126100a65767ffffffffffffffff6004358181116100a957610078903690600401610157565b916024359182116100a657602061009c846100963660048701610157565b906101e3565b6040519015158152f35b80fd5b8280fd5b90601f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0910116810190811067ffffffffffffffff8211176100ee57604052565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b67ffffffffffffffff81116100ee57601f017fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe01660200190565b81601f8201121561019e5780359061016e8261011d565b9261017c60405194856100ad565b8284526020838301011161019e57816000926020809301838601378301015290565b600080fd5b9081518110156101b4570160200190565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b9080518083511061032f576101f78161011d565b9061020560405192836100ad565b8082527fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe093846102348361011d565b01366020850137600090815b838110610299575050505060405161026c81610260602082018095610337565b038581018352826100ad565b519020916102926040519182610286602082018096610337565b039081018352826100ad565b5190201490565b7fff000000000000000000000000000000000000000000000000000000000000006102c482846101a3565b5116831a6102d282876101a3565b537fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff811461030257600101610240565b6024837f4e487b710000000000000000000000000000000000000000000000000000000081526011600452fd5b505050600090565b9081519160005b83811061034f575050016000815290565b806020809284010151818501520161033e56fea2646970667358221220cfe51862e2c18cc21d4a387620f35cdb30716f00a4b665fbf77ecb84920c6fb264736f6c63430008120033';

type StringMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StringMockConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StringMock__factory extends ContractFactory {
  constructor(...args: StringMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string },
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      StringMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): StringMock__factory {
    return super.connect(runner) as StringMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StringMockInterface {
    return new Interface(_abi) as StringMockInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): StringMock {
    return new Contract(address, _abi, runner) as unknown as StringMock;
  }
}
