/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  ICustodian,
  ICustodianInterface,
} from '../../../../contracts/bridge-adapters/ExchangeLayerZeroAdapter.sol/ICustodian';

const _abi = [
  {
    inputs: [],
    name: 'exchange',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ICustodian__factory {
  static readonly abi = _abi;
  static createInterface(): ICustodianInterface {
    return new Interface(_abi) as ICustodianInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICustodian {
    return new Contract(address, _abi, runner) as unknown as ICustodian;
  }
}
