/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  IExchange,
  IExchangeInterface,
} from '../../../../contracts/bridge-adapters/ExchangeLayerZeroAdapter.sol/IExchange';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'quantityInAssetUnits',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'destinationWallet',
        type: 'address',
      },
    ],
    name: 'deposit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class IExchange__factory {
  static readonly abi = _abi;
  static createInterface(): IExchangeInterface {
    return new Interface(_abi) as IExchangeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IExchange {
    return new Contract(address, _abi, runner) as unknown as IExchange;
  }
}
