/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../../common';

export interface ExchangeWithdrawMockInterface extends Interface {
  getFunction(nameOrSignature: 'setCustodian' | 'withdraw'): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'setCustodian',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdraw',
    values: [AddressLike, AddressLike, BigNumberish],
  ): string;

  decodeFunctionResult(
    functionFragment: 'setCustodian',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
}

export interface ExchangeWithdrawMock extends BaseContract {
  connect(runner?: ContractRunner | null): ExchangeWithdrawMock;
  waitForDeployment(): Promise<this>;

  interface: ExchangeWithdrawMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  setCustodian: TypedContractMethod<
    [newCustodian: AddressLike],
    [void],
    'nonpayable'
  >;

  withdraw: TypedContractMethod<
    [
      wallet: AddressLike,
      asset: AddressLike,
      quantityInAssetUnits: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'setCustodian',
  ): TypedContractMethod<[newCustodian: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'withdraw',
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      asset: AddressLike,
      quantityInAssetUnits: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;

  filters: {};
}
