/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  IStargateRouter,
  IStargateRouterInterface,
} from '../../../../contracts/bridge-adapters/ExchangeStargateAdapter.sol/IStargateRouter';

const _abi = [
  {
    inputs: [],
    name: 'factory',
    outputs: [
      {
        internalType: 'contract IStargateFactory',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: '_dstChainId',
        type: 'uint16',
      },
      {
        internalType: 'uint8',
        name: '_functionType',
        type: 'uint8',
      },
      {
        internalType: 'bytes',
        name: '_toAddress',
        type: 'bytes',
      },
      {
        internalType: 'bytes',
        name: '_transferAndCallPayload',
        type: 'bytes',
      },
      {
        components: [
          {
            internalType: 'uint256',
            name: 'dstGasForCall',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'dstNativeAmount',
            type: 'uint256',
          },
          {
            internalType: 'bytes',
            name: 'dstNativeAddr',
            type: 'bytes',
          },
        ],
        internalType: 'struct IStargateRouter.lzTxObj',
        name: '_lzTxParams',
        type: 'tuple',
      },
    ],
    name: 'quoteLayerZeroFee',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: '_dstChainId',
        type: 'uint16',
      },
      {
        internalType: 'uint256',
        name: '_srcPoolId',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_dstPoolId',
        type: 'uint256',
      },
      {
        internalType: 'address payable',
        name: '_refundAddress',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_amountLD',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_minAmountLD',
        type: 'uint256',
      },
      {
        components: [
          {
            internalType: 'uint256',
            name: 'dstGasForCall',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'dstNativeAmount',
            type: 'uint256',
          },
          {
            internalType: 'bytes',
            name: 'dstNativeAddr',
            type: 'bytes',
          },
        ],
        internalType: 'struct IStargateRouter.lzTxObj',
        name: '_lzTxParams',
        type: 'tuple',
      },
      {
        internalType: 'bytes',
        name: '_to',
        type: 'bytes',
      },
      {
        internalType: 'bytes',
        name: '_payload',
        type: 'bytes',
      },
    ],
    name: 'swap',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
] as const;

export class IStargateRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IStargateRouterInterface {
    return new Interface(_abi) as IStargateRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IStargateRouter {
    return new Contract(address, _abi, runner) as unknown as IStargateRouter;
  }
}
