/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  IStargateFactory,
  IStargateFactoryInterface,
} from '../../../../contracts/bridge-adapters/ExchangeStargateAdapter.sol/IStargateFactory';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'getPool',
    outputs: [
      {
        internalType: 'contract IPool',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class IStargateFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IStargateFactoryInterface {
    return new Interface(_abi) as IStargateFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IStargateFactory {
    return new Contract(address, _abi, runner) as unknown as IStargateFactory;
  }
}
