/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStorkVerifier__factory } from './IStorkVerifier__factory';
export { StorkIndexAndOraclePriceAdapter__factory } from './StorkIndexAndOraclePriceAdapter__factory';
