/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainlinkOraclePriceAdapter } from './ChainlinkOraclePriceAdapter';
export type { PythOraclePriceAdapter } from './PythOraclePriceAdapter';
