/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExchangeStargateV2Adapter } from './ExchangeStargateV2Adapter';
export type { ICustodian } from './ICustodian';
export type { IExchange } from './IExchange';
export type { IStargate } from './IStargate';
export type { Owned } from './Owned';
