/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from '../../common';

export interface DepositingInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: 'Deposited' | 'PendingDepositApplied',
  ): EventFragment;
}

export namespace DepositedEvent {
  export type InputTuple = [
    index: BigNumberish,
    sourceWallet: AddressLike,
    destinationWallet: AddressLike,
    quantity: BigNumberish,
  ];
  export type OutputTuple = [
    index: bigint,
    sourceWallet: string,
    destinationWallet: string,
    quantity: bigint,
  ];
  export interface OutputObject {
    index: bigint;
    sourceWallet: string;
    destinationWallet: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingDepositAppliedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    quantity: BigNumberish,
    newExchangeBalance: BigNumberish,
  ];
  export type OutputTuple = [
    wallet: string,
    quantity: bigint,
    newExchangeBalance: bigint,
  ];
  export interface OutputObject {
    wallet: string;
    quantity: bigint;
    newExchangeBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Depositing extends BaseContract {
  connect(runner?: ContractRunner | null): Depositing;
  waitForDeployment(): Promise<this>;

  interface: DepositingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getEvent(
    key: 'Deposited',
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: 'PendingDepositApplied',
  ): TypedContractEvent<
    PendingDepositAppliedEvent.InputTuple,
    PendingDepositAppliedEvent.OutputTuple,
    PendingDepositAppliedEvent.OutputObject
  >;

  filters: {
    'Deposited(uint64,address,address,uint64)': TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    'PendingDepositApplied(address,uint64,int64)': TypedContractEvent<
      PendingDepositAppliedEvent.InputTuple,
      PendingDepositAppliedEvent.OutputTuple,
      PendingDepositAppliedEvent.OutputObject
    >;
    PendingDepositApplied: TypedContractEvent<
      PendingDepositAppliedEvent.InputTuple,
      PendingDepositAppliedEvent.OutputTuple,
      PendingDepositAppliedEvent.OutputObject
    >;
  };
}
