/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from '../../common';

export interface TradingInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: 'LiquidationAcquisitionExecuted' | 'TradeExecuted',
  ): EventFragment;
}

export namespace LiquidationAcquisitionExecutedEvent {
  export type InputTuple = [
    buyWallet: AddressLike,
    sellWallet: AddressLike,
    baseAssetSymbol: string,
    quoteAssetSymbol: string,
    baseQuantity: BigNumberish,
    quoteQuantity: BigNumberish,
    makerSide: BigNumberish,
    makerFeeQuantity: BigNumberish,
    takerFeeQuantity: BigNumberish,
  ];
  export type OutputTuple = [
    buyWallet: string,
    sellWallet: string,
    baseAssetSymbol: string,
    quoteAssetSymbol: string,
    baseQuantity: bigint,
    quoteQuantity: bigint,
    makerSide: bigint,
    makerFeeQuantity: bigint,
    takerFeeQuantity: bigint,
  ];
  export interface OutputObject {
    buyWallet: string;
    sellWallet: string;
    baseAssetSymbol: string;
    quoteAssetSymbol: string;
    baseQuantity: bigint;
    quoteQuantity: bigint;
    makerSide: bigint;
    makerFeeQuantity: bigint;
    takerFeeQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeExecutedEvent {
  export type InputTuple = [
    buyWallet: AddressLike,
    sellWallet: AddressLike,
    baseAssetSymbol: string,
    quoteAssetSymbol: string,
    baseQuantity: BigNumberish,
    quoteQuantity: BigNumberish,
    makerSide: BigNumberish,
    makerFeeQuantity: BigNumberish,
    takerFeeQuantity: BigNumberish,
  ];
  export type OutputTuple = [
    buyWallet: string,
    sellWallet: string,
    baseAssetSymbol: string,
    quoteAssetSymbol: string,
    baseQuantity: bigint,
    quoteQuantity: bigint,
    makerSide: bigint,
    makerFeeQuantity: bigint,
    takerFeeQuantity: bigint,
  ];
  export interface OutputObject {
    buyWallet: string;
    sellWallet: string;
    baseAssetSymbol: string;
    quoteAssetSymbol: string;
    baseQuantity: bigint;
    quoteQuantity: bigint;
    makerSide: bigint;
    makerFeeQuantity: bigint;
    takerFeeQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Trading extends BaseContract {
  connect(runner?: ContractRunner | null): Trading;
  waitForDeployment(): Promise<this>;

  interface: TradingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getEvent(
    key: 'LiquidationAcquisitionExecuted',
  ): TypedContractEvent<
    LiquidationAcquisitionExecutedEvent.InputTuple,
    LiquidationAcquisitionExecutedEvent.OutputTuple,
    LiquidationAcquisitionExecutedEvent.OutputObject
  >;
  getEvent(
    key: 'TradeExecuted',
  ): TypedContractEvent<
    TradeExecutedEvent.InputTuple,
    TradeExecutedEvent.OutputTuple,
    TradeExecutedEvent.OutputObject
  >;

  filters: {
    'LiquidationAcquisitionExecuted(address,address,string,string,uint64,uint64,uint8,int64,uint64)': TypedContractEvent<
      LiquidationAcquisitionExecutedEvent.InputTuple,
      LiquidationAcquisitionExecutedEvent.OutputTuple,
      LiquidationAcquisitionExecutedEvent.OutputObject
    >;
    LiquidationAcquisitionExecuted: TypedContractEvent<
      LiquidationAcquisitionExecutedEvent.InputTuple,
      LiquidationAcquisitionExecutedEvent.OutputTuple,
      LiquidationAcquisitionExecutedEvent.OutputObject
    >;

    'TradeExecuted(address,address,string,string,uint64,uint64,uint8,int64,uint64)': TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
    TradeExecuted: TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
  };
}
